"use client";

import React, {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";

export type Language = "th" | "en";

interface LanguageContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(
  undefined
);

// Minimal translations used by common UI. Extend as needed.
const TRANSLATIONS: Record<Language, Record<string, string>> = {
  th: {
    language_th: "ไทย",
    language_en: "EN",
    buy: "ซื้อ",
    rent: "เช่า",
    real_estate: "อสังหาริมทรัพย์",
    new_real_estate: "อสังหาใหม่",
    new_projects: "โครงการใหม่",
    post_listing: "ลงประกาศ",
    agent: "Agent",
    profile: "โปรไฟล์",
    login: "เข้าสู่ระบบ",
    search: "ค้นหา",
    search_placeholder: "ค้นหาโครงการ รถไฟฟ้า เขต...",

    // Common
    back: "ย้อนกลับ",
    back_to_home: "กลับสู่หน้าหลัก",
    loading: "กำลังโหลด...",
    error_loading: "เกิดข้อผิดพลาดในการโหลดข้อมูล",
    confirm: "ยืนยัน",
    close: "ปิด",
    processing: "กำลังดำเนินการ...",

    // Featured Property
    featured_property_title: "โครงการใหม่ใกล้รถไฟฟ้า การเดินทางสะดวก",
    featured_property_price: "เริ่มต้น 5.2 ล้านบาท",
    featured_property_total_units: "จำนวนยูนิตทั้งหมด",
    featured_property_room_size: "ขนาดห้อง",
    featured_property_price_per_sqm: "ราคาต่อตารางเมตร",
    featured_property_maintenance_fee: "ค่าบำรุงรักษา",
    featured_property_view_details: "ดูรายละเอียดโครงการ",
    dashboard_title: "แดชบอร์ด",
    please_login: "กรุณาเข้าสู่ระบบ",

    // Sidebar menu items
    sidebar_dashboard: "แดชบอร์ด",
    sidebar_my_account: "บัญชีของฉัน",
    sidebar_my_listings: "ประกาศของฉัน",
    sidebar_favorites: "รายการที่สนใจ",
    sidebar_packages: "แพ็กเกจ",
    sidebar_notifications: "แจ้งเตือน",
    sidebar_logout: "ออกจากระบบ",

    // Header navigation menu
    header_buy: "ซื้อ",
    header_sell: "ขาย",
    header_rent: "เช่า",
    header_real_estate: "อสังหาริมทรัพย์",
    header_new_real_estate: "อสังหาใหม่",
    header_new_projects: "โครงการใหม่",
    header_post_listing: "ลงประกาศ",
    header_profile: "โปรไฟล์",
    header_language_thai: "ภาษาไทย",
    header_language_english: "English",
    you_are_not_logged_in_description:
      "คุณยังไม่ได้เข้าสู่ระบบ กรุณาเข้าสู่ระบบเพื่อใช้งานแดชบอร์ด",
    admin_dashboard: "แดชบอร์ดผู้ดูแลระบบ",
    welcome_admin: "ยินดีต้อนรับ ผู้ดูแลระบบ",
    manage_my_account: "จัดการบัญชีของฉัน",
    open_super_admin_login_new_window: "เข้าสู่ระบบ Super Admin (หน้าต่างใหม่)",
    note_super_admin:
      "หมายเหตุ: ระบบ Super Admin แยกออกจากหน้าหลัก กรุณาใช้ลิงก์ด้านบนเพื่อเข้าสู่ระบบแยกต่างหาก",
    checking_user_info: "กำลังตรวจสอบข้อมูลผู้ใช้...",
    please_wait_redirect:
      "กรุณารอสักครู่ระบบกำลังนำท่านไปยังแดชบอร์ดที่เหมาะสม",
    welcome: "ยินดีต้อนรับ",
    redirecting: "ระบบกำลังนำท่านไปยังหน้าที่เหมาะสม...",
    logout: "ออกจากระบบ",
    switch_to_customer: "สลับไปยังบัญชีลูกค้า",
    switch_to_agent: "สลับไปยังบัญชีตัวแทน",

    // Favorites
    favorites_title: "รายการที่สนใจ",
    search_placeholder_favorites: "ค้นหาโครงการ,ราคา",
    compare_price: "เปรียบเทียบราคา",
    all_properties: "อสังหาทั้งหมด",
    sale: "ขาย",
    no_favorites_title: "ยังไม่มีรายการโปรด",
    no_favorites_desc:
      "เริ่มเพิ่มอสังหาริมทรัพย์ที่คุณสนใจเข้าสู่รายการโปรดกันเถอะ",
    start_search: "เริ่มค้นหาอสังหาฯ",

    // Favorites page specific
    favorites_page_title: "รายการที่สนใจ",
    favorites_compare_selected: "เปรียบเทียบรายการที่เลือก",
    favorites_items_count: "รายการ",
    favorites_table_close: "ปิดตาราง",
    favorites_table_minimize: "คลิกเพื่อขยายตาราง",
    favorites_compare_alert: "กรุณาเลือกอย่างน้อย 2 รายการเพื่อเปรียบเทียบ",
    favorites_remove_success: "ลบออกจากรายการโปรดแล้ว",
    favorites_add_success: "เพิ่มเข้ารายการโปรดแล้ว",
    favorites_remove_error: "เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง",
    favorites_share_success: "แชร์สำเร็จ!",
    favorites_copy_success: "คัดลอกลิงก์เรียบร้อยแล้ว!",
    favorites_share_error: "ไม่สามารถแชร์ได้ กรุณาลองใหม่อีกครั้ง",
    favorites_login_required: "กรุณาเข้าสู่ระบบก่อนใช้งานฟีเจอร์นี้",
    favorites_rent: "ให้เช่า",
    favorites_sale: "ขาย",
    favorites_popular: "ยอดนิยม",
    favorites_featured: "เด่น",
    favorites_views: "ดู",
    favorites_times: "ครั้ง",
    favorites_remove_from_favorites: "ลบออกจากรายการโปรด",
    favorites_add_to_favorites: "เพิ่มเข้ารายการโปรด",
    favorites_share_property: "แชร์ประกาศนี้",
    favorites_select_for_compare: "เลือกเพื่อเปรียบเทียบ",
    favorites_deselect: "ยกเลิกการเลือก",
    favorites_rooms: "ห้อง",
    favorites_cars: "คัน",
    favorites_others: "อื่นๆ",
    favorites_no_data: "ไม่มีข้อมูล",
    favorites_project_facilities: "สิ่งอำนวยความสะดวกโครงการ",
    favorites_area_size_label: "ขนาดพื้นที่",
    favorites_usable_area_label: "พื้นที่ใช้สอย",
    favorites_comparison_list_label: "รายการ",
    favorites_property_facilities_label: "สิ่งอำนวยความสะดวก",
    list: "รายการ",
    price: "ราคา",
    bedrooms: "ห้องนอน",
    bathrooms: "ห้องน้ำ",
    area_sqm: "พื้นที่ (ตร.ม.)",
    parking_spaces: "จำนวนที่จอดรถ",
    house_condition: "สภาพบ้าน",
    highlight: "ไฮไลท์",
    nearby_places: "สถานที่ใกล้เคียง",
    description: "คำอธิบาย",
    project_facilities: "สิ่งอำนวยความสะดวกโครงการ",
    created_date: "วันที่สร้าง",
    unspecified: "ไม่ระบุ",
    // Property tags
    tag_new_project: "โครงการใหม่",
    tag_housing_estate: "หมู่บ้าน",
    tag_new_housing_estate: "โครงการหมู่บ้านใหม่",

    // Property card & detail
    property_card_area_unit: "ตร.ม.",
    property_card_bedrooms_label: "ห้องนอน",
    property_card_bathrooms_label: "ห้องน้ำ",
    property_card_parking_label: "จอดรถ",
    property_card_badge_sale_rent: "ขาย/เช่า",
    property_card_badge_rent: "ให้เช่า",
    property_card_badge_sale: "ขาย",
    property_card_price_suffix: "บาท",
    property_card_price_per_month_suffix: "/ เดือน",
    property_card_view_suffix: "ครั้ง",
    property_card_negotiation_name_label: "ชื่อ :",
    property_card_negotiation_price_label: "ราคาที่เสนอ :",
    property_card_negotiation_reason_label: "เหตุผลที่เสนอ :",
    property_card_negotiation_phone_label: "เบอร์ติดต่อ :",
    property_card_negotiation_email_label: "อีเมล :",
    property_card_appointment_name_label: "ชื่อ :",
    property_card_appointment_phone_label: "เบอร์ติดต่อ :",
    property_card_appointment_email_label: "อีเมล :",
    property_card_appointment_date_label: "วันนัดหมาย :",
    property_card_appointment_note_label: "หมายเหตุ :",
    property_card_download_document: "ดาวน์โหลดเอกสาร",
    property_card_create_contract: "สร้างสัญญา",
    property_card_confirm_button: "ยืนยัน",
    property_card_reject_button: "ปฏิเสธ",
    property_card_status_sold: "ขายแล้ว",
    property_card_status_rented: "ให้เช่าแล้ว",
    property_card_view_on_map: "ดูบนแผนที่",
    property_card_update_button: "อัปเดต",
    property_card_contract_heading: "สัญญาซื้อขาย",
    property_card_contract_buyer_label: "ผู้ซื้อ:",
    property_card_contract_seller_label: "ผู้ขาย:",
    property_card_contract_property_label: "ทรัพย์สิน:",
    property_card_contract_price_label: "ราคา:",
    property_card_contract_date_label: "วันที่:",
    property_card_confirmation_title: "ยืนยันการนัดหมาย",
    property_card_confirmation_message: "คุณต้องการยืนยันการนัดหมายนี้หรือไม่?",
    property_card_confirm_success_title: "ยืนยันสำเร็จ",
    property_card_confirm_success_message: "การยืนยันนัดหมายเสร็จสิ้นแล้ว",
    property_card_cancel_title: "ยกเลิกการนัดหมาย",
    property_card_cancel_message: "คุณต้องการยกเลิกการนัดหมายนี้หรือไม่?",
    property_card_cancel_success_title: "ยกเลิกสำเร็จ",
    property_card_cancel_success_message: "การยกเลิกนัดหมายเสร็จสิ้นแล้ว",
    property_card_price_label: "ราคา",
    property_card_share_failure: "ไม่สามารถแชร์ได้",
    property_card_clipboard_success: "คัดลอกลิงก์แล้ว",
    property_card_share_prefix: "ราคา",

    property_detail_loading_description:
      "กรุณารอสักครู่ ระบบกำลังดึงข้อมูลทรัพย์สิน",
    property_detail_error_title: "เกิดข้อผิดพลาด",
    property_detail_error_description: "ไม่สามารถโหลดข้อมูลทรัพย์สินได้",
    property_detail_not_found_title: "ไม่พบข้อมูลทรัพย์สิน",
    property_detail_not_found_description:
      "ทรัพย์สินที่คุณต้องการดูไม่มีอยู่ในระบบ",
    property_detail_reset_gallery_tooltip: "คลิกเพื่อกลับไปรูปแรก",
    property_detail_price_label: "ราคา :",
    property_detail_area_title: "พื้นที่ใช้สอย",
    property_detail_features_area: "พื้นที่",
    property_detail_features_bedrooms: "ห้องนอน",
    property_detail_features_bathrooms: "ห้องน้ำ",
    property_detail_features_parking: "จอดรถ",
    property_detail_features_condition: "สภาพบ้าน",
    property_detail_features_type: "ประเภท",
    property_detail_highlight_title: "จุดเด่นอสังหาฯ",
    property_detail_highlight_empty: "ไม่มีข้อมูลจุดเด่น",
    property_detail_read_more: "ดูทั้งหมด",
    property_detail_read_less: "ดูน้อยลง",
    property_detail_description_title: "เกี่ยวกับอสังหาฯ",
    property_detail_description_empty: "ไม่มีข้อมูลรายละเอียด",
    property_detail_location_title: "ที่ตั้งอสังหาฯ",
    property_detail_similar_title: "อสังหาฯ ใกล้เคียง",
    property_detail_scroll_left: "เลื่อนไปซ้าย",
    property_detail_scroll_right: "เลื่อนไปขวา",
    property_detail_no_similar: "ไม่พบอสังหาริมทรัพย์ที่คล้ายกัน",
    property_detail_contact_title: "สอบถามเกี่ยวกับทรัพย์สิน",
    property_detail_agent_label: "ตัวแทนทรัพย์สิน",
    property_detail_view_phone: "ดูเบอร์โทร",
    property_detail_toast_success_added: "เพิ่มเข้ารายการโปรดแล้ว",
    property_detail_toast_success_removed: "ลบออกจากรายการโปรดแล้ว",
    property_detail_toast_error: "เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง",
    property_detail_share_not_supported: "เบราว์เซอร์ของคุณไม่รองรับการแชร์",
    property_detail_login_message: "กรุณาเข้าสู่ระบบ",
    property_detail_payment_required: "กรุณาชำระเงินเพื่อเปิดการติดต่อผู้ขาย",
    property_detail_modal_close: "ปิด",
    property_detail_modal_message_login: "กรุณาเข้าสู่ระบบ",
    property_detail_modal_message_payment:
      "กรุณาชำระเงินเพื่อเปิดการติดต่อผู้ขาย",
    property_detail_toast_clipboard_success: "คัดลอกลิงก์เรียบร้อยแล้ว",
    property_detail_load_more_icon: "ดูเพิ่ม",
    property_detail_agent_role: "ตัวแทนทรัพย์สิน",
    property_detail_price_not_available: "ไม่ระบุราคา",
    property_detail_area_unit: "ตร.ม.",
    property_detail_feature_unit: "ตร.ม.",
    property_detail_feature_type_sale_rent: "ขาย/เช่า",
    property_detail_back_button: "ย้อนกลับ",
    property_detail_notify_phone_success: "แจ้งเตือนสำเร็จ",
    property_detail_notify_phone_error: "ไม่สามารถแจ้งเตือนได้",
    property_detail_loading_title: "กำลังโหลดข้อมูล...",
    property_detail_error_back_home: "กลับไปหน้าหลัก",
    property_detail_contact_button_label: "ดูเบอร์โทร",
    property_detail_mobile_contact_title: "สอบถามเกี่ยวกับทรัพย์สิน",
    property_detail_unavailable: "N/A",
    property_detail_address_unavailable: "ไม่ระบุที่อยู่",
    property_detail_default_share_title: "อสังหาฯ",
    property_detail_project_name_unavailable: "ไม่ระบุชื่อโครงการ",
    property_detail_default_property_title: "ทรัพย์สิน",

    // Notifications
    notifications: "แจ้งเตือน",
    all: "ทั้งหมด",
    unread: "ยังไม่ได้อ่าน",
    no_notifications: "ไม่มีการแจ้งเตือน",
    previous_notifications: "ดูการแจ้งเตือนก่อนหน้า",
    show_all_notifications: "แสดงรายการแจ้งเตือนทั้งหมด",
    collapse_notifications: "ย่อรายการแจ้งเตือน",
    from: "จาก:",
    system: "ระบบ",
    read_label: "อ่านแล้ว",
    property_not_found: "ไม่พบรายการนี้",
    customer_already_exists: "ลูกค้าคนนี้มีรายการนี้อยู่แล้ว",
    duplicate_customer_title: "แจ้งเตือน",
    duplicate_customer_message: "ลูกค้าคนนี้มีรายการนี้อยู่แล้ว",
    update_failed: "ไม่สามารถอัปเดตข้อมูลได้",
    customer_added_success: "เพิ่มลูกค้าสำเร็จ",
    customer_notification_title: "เช่าสำเร็จ",
    customer_notification_message: "คุณได้รับการเพิ่มเป็นเจ้าของรายการนี้แล้ว",

    // Listings
    my_listings: "ประกาศของฉัน",
    search_placeholder_listings: "ค้นหาโครงการ, ราคา",
    add_listing: "เพิ่มประกาศ",
    filters: "ตัวกรอง",
    view_all: "ดูทั้งหมด",
    negotiating: "ขอต่อรองราคา",
    scheduling: "นัดหมาย",
    contracted: "ทำสัญญาแล้ว",
    update_every_3_months: "อัพเดตทุก 3 เดือน",
    checking_user_status: "กำลังตรวจสอบสถานะผู้ใช้...",
    loading_listings: "กำลังโหลดข้อมูลประกาศ...",
    not_logged_in_view_my_listings: "โปรดเข้าสู่ระบบเพื่อดูประกาศของคุณ",
    search_no_results: "ไม่พบประกาศที่ตรงกับการค้นหา",
    empty_all: "ยังไม่มีประกาศในระบบ",
    empty_negotiating: "ไม่พบประกาศที่อยู่ระหว่างการต่อรองราคา",
    empty_scheduling: "ไม่พบประกาศที่อยู่ในสถานะนัดหมาย",
    empty_contracted: "ไม่พบประกาศที่ทำสัญญาแล้ว",
    empty_update_reminder: "ไม่พบประกาศที่ต้องอัปเดต",
    show_filters: "แสดงตัวกรอง",
    loading_negotiations: "กำลังโหลดคำขอต่อรอง...",
    loading_appointments: "กำลังโหลดนัดหมาย...",
    no_negotiations_message: "ยังไม่มีคำขอต่อรอง",
    no_appointments_message: "ยังไม่มีนัดหมาย",
    no_contracts_detail: "พบ {count} นัดหมาย แต่ไม่มีข้อมูลสัญญา",
    listings_filtered_out_detail: "พบ {count} ประกาศ แต่ถูกกรองออกทั้งหมด",
    listing_hidden_due_status:
      "ประกาศนี้ถูกซ่อนเนื่องจากสถานะขาย/เช่า ครบ 3 วัน",
    status_sold_label: "ขายไปแล้ว",
    status_rented_label: "เช่าไปแล้ว",
    listing_expiry_warning:
      "ประกาศจะถูกลบในอีก {days} วัน เนื่องจากประกาศนี้{status}",
    listing_no_description: "ไม่มีคำอธิบาย",
    listing_no_highlight: "ไม่มีข้อมูลไฮไลท์",
    listing_no_nearby_info: "ไม่มีข้อมูลพื้นที่ใกล้เคียง",
    action_edit: "แก้ไข",
    action_delete: "ลบ",
    action_mark_as_sold: "ทำเครื่องหมายว่าขายแล้ว",
    action_mark_as_rented: "ทำเครื่องหมายว่าให้เช่าแล้ว",
    delete_confirmation_title: "ยืนยันการลบ",
    delete_confirmation_body:
      "คุณต้องการลบประกาศนี้หรือไม่? การลบจะไม่สามารถกู้คืนได้",
    edit_listing_modal_title: "แก้ไขประกาศ",
    edit_listing_modal_body: "คุณต้องการแก้ไขประกาศนี้หรือไม่?",
    update_form_property_not_found: "ไม่พบประกาศที่ต้องการอัปเดต",
    error_delete_listing: "เกิดข้อผิดพลาดในการลบประกาศ",
    error_update_status: "เกิดข้อผิดพลาดในการอัพเดทสถานะ",
    notification_expiring_listing: "ประกาศใกล้หมดอายุ",
    no_update_cards_customer: "ไม่พบการ์ดที่เกี่ยวข้องกับคุณ",
    no_update_cards_rented: 'ไม่พบการ์ดที่มีสถานะ "rented"',
    no_data: "ไม่มีข้อมูล",
    account_title: "ข้อมูลบัญชี",
    account_profile_tab: "ข้อมูลโปรไฟล์",
    account_security_tab: "ความปลอดภัย",
    account_notifications_tab: "การแจ้งเตือน",
    account_manage_profile: "จัดการข้อมูลส่วนตัวของคุณ",
    account_manage_role_info: "ข้อมูลเพิ่มเติมตามบทบาทของคุณ",
    account_loading: "กำลังโหลด...",
    account_loading_agent: "กำลังโหลดข้อมูลตัวแทน...",
    account_loading_customer: "กำลังโหลดข้อมูลลูกค้า...",
    account_agent_not_found: "ไม่พบข้อมูลตัวแทน",
    account_customer_not_found: "ไม่พบข้อมูลลูกค้า",
    account_no_profile_role: "ไม่มีข้อมูลโปรไฟล์สำหรับบทบาทนี้",
    account_security_title: "ความปลอดภัย",
    account_security_desc: "เปลี่ยนรหัสผ่านและจัดการความปลอดภัยของบัญชี",
    account_password_label: "รหัสผ่าน",
    account_password_hint: "หากต้องการเปลี่ยนรหัสผ่าน กรุณากดปุ่มด้านล่าง",
    account_change_password: "เปลี่ยนรหัสผ่าน",
    account_notifications_title: "การแจ้งเตือน",
    account_notifications_desc: "จัดการช่องทางการรับข่าวสารจากเรา",
    account_notifications_email: "การแจ้งเตือนทางอีเมล",
    account_notifications_email_desc: "รับข่าวสารและอัปเดตผ่านทางอีเมลของคุณ",
    account_notifications_sms: "การแจ้งเตือนทาง SMS",
    account_notifications_sms_desc: "รับการแจ้งเตือนที่สำคัญผ่านทางข้อความ SMS",
    account_profile_info: "ข้อมูลโปรไฟล์",
    account_edit_first_name: "แก้ไขชื่อ",
    account_edit_last_name: "แก้ไขนามสกุล",
    account_edit_phone: "แก้ไขเบอร์โทร",
    account_role_label: "บทบาท",
    account_agent_company_name: "ชื่อบริษัท",
    account_agent_license: "หมายเลขใบอนุญาต",
    account_agent_address: "ที่อยู่",
    account_agent_property_types: "ประเภทอสังหาฯ",
    account_agent_service_areas: "พื้นที่ให้บริการ",
    account_agent_status: "สถานะ",
    account_customer_address: "ที่อยู่",
    account_customer_preferred_location: "สถานที่ที่สนใจ",
    account_customer_budget_range: "งบประมาณ",
    account_customer_interested_types: "ประเภทอสังหาที่สนใจ",
    agent_dashboard_title: "แดชบอร์ดตัวแทน",
    agent_dashboard_loading: "กำลังโหลดแดชบอร์ด...",
    agent_dashboard_missing_id: "กรุณาระบุรหัส Agent",
    agent_dashboard_properties_status: "จำนวนประกาศตามสถานะ",
    agent_dashboard_properties_posted: "จำนวนประกาศใน 12 เดือนที่ผ่านมา",
    agent_dashboard_properties_dataset: "ประกาศ",
    agent_dashboard_top_categories: "หมวดหมู่",
    agent_dashboard_appointments_status: "จำนวนนัดหมาย",
    agent_dashboard_negotiations_status: "จำนวนการขอต่อรอง",
    agent_dashboard_appointments_last_12m: "นัดหมาย (12 เดือนที่ผ่านมา)",
    agent_dashboard_appointments_dataset: "นัดหมาย",
    agent_dashboard_notifications_last_30d: "การแจ้งเตือน (30 วันที่ผ่านมา)",
    agent_dashboard_notifications_dataset: "การแจ้งเตือน",

    // Modals
    accept_offer_question: "ต้องการยอมรับข้อเสนอ?",
    accept_offer_note:
      "เมื่อกดปุ่มยืนยัน ระบบจะทำการส่งแจ้งเตือนไปยังผู้เสนอราคา",
    accept_offer_success: "ยอมรับข้อเสนอเรียบร้อย!",
    accept_offer_success_note:
      "ระบบจะทำการส่งแจ้งเตือนไปยังผู้เสนอราคา และการ์ดจะหายไปจากหน้านี้",
    reject_offer_question: "ต้องการปฏิเสธข้อเสนอ?",
    please_specify_reason: "กรุณาระบุเหตุผล",
    other_reason: "อื่นๆ (โปรดระบุ)",
    enter_other_reason: "กรอกเหตุผลอื่นๆ",
    reject_confirm: "ยืนยันการปฏิเสธ",
    reject_success: "ปฏิเสธข้อเสนอ สำเร็จ!",

    // Home page
    loading_properties: "กำลังโหลดข้อมูลอสังหาริมทรัพย์...",
    home_new_properties_title:
      "อสังหามาใหม่ล่าสุด! พร้อมเข้าอยู่/ลงทุน ราคาดี ทำเลเด่น",
    home_rental_properties_title:
      "ประกาศเช่า บ้าน/คอนโด/ที่ดิน พร้อมเข้าอยู่ ราคาดี ทำเลเยี่ยม!",
    home_sale_properties_title:
      "ประกาศขาย บ้าน/คอนโด/ที่ดิน ทำเลทอง ลงทุนก็คุ้ม อยู่เองก็สบาย",
    home_sale_rent_properties_title:
      "ประกาศ เช่า/ขาย บ้าน/คอนโดทำเลทอง ใกล้ห้างฯ ร้านอาหาร แหล่งไลฟ์สไตล์ครบครัน",
    popular_locations: "ทำเลยอดนิยม",
    location_sukhumvit: "สุขุมวิท",
    location_rama9: "พระราม 9",
    location_ladprao: "ห้าแยกลาดพร้าว",
    location_sathorn: "สาทร",

    // Map page
    back_label: "ย้อนกลับ",
    map_search_placeholder: "ค้นหาทำเล, โครงการ, หรือคีย์เวิร์ด",
    property_type_all: "ทุกประเภทอสังหาฯ",
    property_type_condo: "คอนโด",
    property_type_house: "บ้าน",
    property_type_townhouse: "ทาวน์เฮาส์",
    property_type_land: "ที่ดิน",
    property_type_commercial: "เชิงพาณิชย์",
    listing_type_all: "ประกาศทั้งหมด",
    listing_type_rent: "ประกาศเช่า",
    listing_type_sale: "ประกาศขาย",
    price_label: "ราคา",
    sort_new_old: "โครงการ (ใหม่-เก่า)",
    sort_price_asc: "ราคา (ต่ำ-สูง)",
    sort_price_desc: "ราคา (สูง-ต่ำ)",
    loading_map: "กำลังโหลดแผนที่...",
    not_found_list: "ไม่พบรายการที่ค้นหา",

    // Add-property progress
    progress_step1_intro: "แนะนำการลงประกาศ",
    progress_step2_basic: "กรอกรายละเอียดเบื้องต้น",
    progress_step3_property: "กรอกรายละเอียดอสังหาฯ",
    progress_step4_review: "ตรวจสอบข้อมูล",

    // Project titles and descriptions
    project_grand_title: "เดอะ แกรนด์ เรสซิเดนซ์",
    project_grand_location: "สุขุมวิท - กรุงเทพฯ",
    project_grand_description:
      "โครงการคอนโดมิเนียมสไตล์โมเดิร์นลักชัวรี่ ใกล้รถไฟฟ้า ตั้งอยู่ในทำเลศักยภาพ ใกล้ห้างสรรพสินค้า และสิ่งอำนวยความสะดวกครบครัน",
    project_grand_total_units: "406 ยูนิต",
    project_grand_room_size: "27-32.7 ตร.ม.",
    project_grand_price_per_sqm: "(57,098 บาท/ตร.ม.)",
    project_grand_maintenance_fee: "18 บาท",
    project_grand_price: "เริ่มต้น 5.5 ล้านบาท",
    project_luxe_title: "เดอะ ลักซ์ คอนโดมิเนียม",
    project_luxe_location: "พระราม 9 - กรุงเทพฯ",
    project_luxe_description:
      "คอนโดมิเนียมหรูหราใจกลางเมือง ดีไซน์ระดับพรีเมียม ใช้วัสดุคุณภาพสูง สิ่งอำนวยความสะดวกครบครัน ใกล้ MRT และทางด่วน",
    project_luxe_total_units: "325 ยูนิต",
    project_luxe_room_size: "35-65 ตร.ม.",
    project_luxe_price_per_sqm: "(85,000 บาท/ตร.ม.)",
    project_luxe_maintenance_fee: "22 บาท",
    project_luxe_price: "เริ่มต้น 6.8 ล้านบาท",
    project_riverside_title: "ริเวอร์ไซด์ วิลล่า",
    project_riverside_location: "เจริญนคร - กรุงเทพฯ",
    project_riverside_description:
      "บ้านเดี่ยวติดแม่น้ำเจ้าพระยา บรรยากาศสงบ มองเห็นวิวสวยงาม พื้นที่ใช้สอยกว้างขวาง การเดินทางสะดวกทั้งทางน้ำและทางบก",
    project_riverside_total_units: "150 ยูนิต",
    project_riverside_room_size: "250-350 ตร.ม.",
    project_riverside_price_per_sqm: "(120,000 บาท/ตร.ม.)",
    project_riverside_maintenance_fee: "35 บาท",
    project_riverside_price: "เริ่มต้น 15.5 ล้านบาท",

    // Footer
    footer_company_name: "Teedin",
    footer_company_description:
      "แพลตฟอร์มอสังหาริมทรัพย์ที่ช่วยให้คุณค้นหาบ้าน คอนโด และที่ดินได้ง่ายขึ้น",
    footer_about_us: "เกี่ยวกับเรา",
    footer_about_teedin: "เกี่ยวกับ Teedin",
    footer_contact_us: "ติดต่อเรา",
    footer_join_us: "ร่วมงานกับเรา",
    footer_our_services: "บริการของเรา",
    footer_buy_house: "ซื้อบ้าน",
    footer_rent_house: "เช่าบ้าน",
    footer_sell_house: "ขายบ้าน",
    footer_appraise_price: "ประเมินราคา",
    footer_follow_us: "ติดตามเรา",
    footer_social_facebook: "Facebook",
    footer_social_instagram: "Instagram",
    footer_social_twitter: "Twitter",
    footer_copyright: "2023 Teedin. สงวนลิขสิทธิ์",
    footer_privacy_policy: "นโยบายความเป็นส่วนตัว",

    // Rental types
    rental_type_rent: "เช่า",
    rental_type_sale: "ขาย",

    // Price filter
    price_range_label: "ช่วงราคา (บาท)",
    min_price_label: "ราคาที่เลือก",
    max_price_label: "ราคาสูงสุด",
    reset_button: "รีเซ็ต",
    apply_button: "ใช้งาน",

    // Refresh button
    refresh_data: "รีเฟรชข้อมูล",

    // Pagination
    previous_page: "← ก่อนหน้า",
    next_page: "ถัดไป →",
    page_label: "หน้า",
    of_label: "จาก",
    results_title: "ผลการค้นหาอสังหาริมทรัพย์",
    results_showing: "แสดง",
    results_of: "จาก",
    // All properties page
    all_props_search_placeholder: "ค้นหาทำเล, โครงการ หรือคีย์เวิร์ด",
    filter_type_label: "ประเภท",
    filter_rental_label: "เช่า/ขาย",
    filter_rooms_label: "ห้องนอน",
    filter_price_label: "ราคา",
    show_map: "แสดงแผนที่",
    clear_filters: "ล้างตัวกรอง",
    prev: "ก่อนหน้า",
    next: "ถัดไป",
    no_properties_title: "ไม่พบอสังหาริมทรัพย์",
    no_properties_from_db_title: "ไม่มีการลงประกาศ",
    no_properties_from_db_desc: "ขณะนี้ยังไม่มีประกาศจากฐานข้อมูล",
    try_adjust_filters: "ลองปรับตัวกรองหรือคำค้นหา",

    // MapPicker component
    map_pick_open_edit: "คลิกเพื่อแก้ไขตำแหน่ง",
    map_pick_open_select: "คลิกเพื่อเลือกตำแหน่งบนแผนที่",
    map_pick_not_selected: "ยังไม่ได้เลือกตำแหน่ง",
    map_pick_title: "เลือกตำแหน่งบนแผนที่",
    map_pick_search_placeholder: "ค้นหาที่อยู่ เช่น สุขุมวิท กรุงเทพฯ",
    map_pick_search_button: "ค้นหา",
    map_pick_loading: "กำลังโหลดแผนที่...",
    map_pick_instructions:
      "คลิกบนแผนที่เพื่อเลือกตำแหน่ง หรือค้นหาที่อยู่ด้านบน",
    map_pick_selected_address_label: "ที่อยู่ที่เลือก:",
    map_pick_coordinates_label: "พิกัด:",
    map_pick_select_prompt: "กรุณาเลือกตำแหน่งบนแผนที่",
    cancel: "ยกเลิก",
    confirm_select_location: "ยืนยันเลือกตำแหน่ง",
    map_pick_search_not_found: "ไม่พบที่อยู่ที่ค้นหา กรุณาลองใหม่อีกครั้ง",
    address_not_found: "ที่อยู่ไม่พบ",

    // Add-property Step1 Introduction
    step1_heading: "🌟 ลงประกาศอสังหาริมทรัพย์ง่าย ๆ ในไม่กี่ขั้นตอน! 🌟",
    step1_intro_line1_prefix:
      "Teedin Easy ช่วยให้คุณลงประกาศได้สะดวก รวดเร็ว โดยใช้",
    step1_intro_maps: " แผนที่ (Maps) ",
    step1_intro_line1_suffix: "ในการค้นหาอสังหาริมทรัพย์ เพียงแค่",
    step1_intro_pin: " ปักหมุด ",
    step1_intro_line2:
      "ระบบจะดึงข้อมูลที่อยู่และรายละเอียดโครงการให้อัตโนมัติ ลดเวลาการกรอกข้อมูล ให้คุณขายหรือให้เช่าอสังหาริมทรัพย์ได้ง่ายขึ้น!",
    step1_how_title: "✅ วิธีลงประกาศง่าย ๆ",
    step1_step1: "1. ต้องการ ขาย หรือ เช่า หรือ ทั้งขายและเช่า",
    step1_step2:
      "2. เลือกประเภทอสังหาริมทรัพย์ – บ้าน, คอนโด, ที่ดิน หรืออื่น ๆ",
    step1_step3: "3. ปักหมุดบนแผนที่ – ระบุตำแหน่งของอสังหาริมทรัพย์",
    step1_step4:
      "4. ตรวจสอบข้อมูล – ระบบดึงข้อมูลโครงการอัตโนมัติ แก้ไขได้ตามต้องการ",
    step1_step5: "5. อัปโหลดรูปภาพ – เพิ่มภาพอสังหาริมทรัพย์ให้น่าสนใจ",
    step1_step6:
      "6. กดเผยแพร่ – ประกาศของคุณจะพร้อมแสดงให้ผู้ซื้อ/เช่าเห็นทันที!",
    step1_why_title: "🔍 ทำไมต้อง Teedin Easy?",
    step1_why_1: "✅ ปักหมุดง่าย – ไม่ต้องกรอกที่อยู่เอง ระบบหาให้เลย!",
    step1_why_2: "✅ ลดเวลาลงประกาศ – มีข้อมูลโครงการให้แก้ไขนิดเดียว",
    step1_why_3:
      "✅ เข้าถึงลูกค้าได้เร็ว – แสดงประกาศของคุณให้คนที่กำลังมองหาอสังหาฯ ได้เห็น",
    step1_start_button: "เริ่มกรอกข้อมูล",
    step1_alert_title: "ยันยันตัวตนเพื่อลงประกาศ",
    step1_alert_desc: "กรุณาสมัครเป็น Agent ก่อนดำเนินการลงประกาศ",
    step1_register_agent: "สมัคร Agent",
    step1_switch_role_title: "สลับไปยังบัญชีตัวแทนเพื่อลงประกาศ",
    step1_switch_role_desc:
      "คุณกำลังใช้งานในฐานะลูกค้า กรุณาสลับไปยังบัญชีตัวแทนเพื่อดำเนินการลงประกาศ",
    step1_switch_to_agent: "สลับเป็น Agent",

    // Identity Verification Modal (Agent Register)
    agent_modal_title: "ยืนยันตัวตนเพื่อลงประกาศ",
    verify_step1_personal: "ข้อมูลส่วนตัว",
    verify_step2_verification: "ยืนยันตัวตน",
    verify_first_name: "ชื่อ *",
    verify_last_name: "นามสกุล *",
    verify_phone: "เบอร์โทร *",
    verify_phone_placeholder: "0909809567",
    verify_property_types_label: "ประเภทอสังหาที่ต้องการลงประกาศ *",
    verify_property_type_sell: "ขาย",
    verify_property_type_rent: "เช่า",
    verify_property_type_auction: "ประมูล",
    verify_otp_label: "รหัส OTP *",
    verify_otp_placeholder: "กรอกรหัส 6 หลัก",
    verify_send_otp: "ส่งรหัส OTP",
    verify_resend_otp: "ส่งรหัสอีกครั้ง",
    verify_otp_countdown: "ส่งอีกครั้งใน {seconds} วินาที",
    verify_otp_sent_success: "ส่งรหัส OTP ไปยัง {phone} เรียบร้อยแล้ว",
    verify_otp_verified: "ยืนยันรหัสสำเร็จ",
    verify_otp_invalid: "รหัส OTP ไม่ถูกต้อง",
    verify_submit_button: "ยืนยันตัวตนและเริ่มลงประกาศ",
    verify_submitting: "กำลังยืนยันตัวตน...",
    verify_error_first_name: "กรุณากรอกชื่อ",
    verify_error_last_name: "กรุณากรอกนามสกุล",
    verify_error_phone: "กรุณากรอกเบอร์โทร",
    verify_error_phone_format: "กรุณากรอกเบอร์โทรให้ถูกต้อง (10 หลัก)",
    verify_error_select_property_type: "กรุณาเลือกประเภทอสังหาอย่างน้อย 1 ประเภท",
    verify_error_otp_required: "กรุณากรอกรหัส OTP",
    verify_error_verify_otp: "กรุณายืนยัน OTP ก่อนดำเนินการต่อ",
    verify_success_title: "ยืนยันตัวตนสำเร็จ!",
    verify_success_message: "คุณสามารถเริ่มลงประกาศอสังหาริมทรัพย์ได้แล้ว",


    // Add-property page
    add_prop_loading: "กำลังโหลด...",
    add_prop_data_restored: "ข้อมูลฟอร์มถูกกู้คืนแล้ว",
    add_prop_success_title: "ลงประกาศสำเร็จ!",
    add_prop_success_desc_line1: "กรุณารอการตรวจสอบประกาศสักครู่",
    add_prop_success_desc_line2: "หลังได้รับการอนุมัติเพื่อจึงลงประกาศ",
    add_prop_view_my_listings: "ดูประกาศของฉัน",
    add_prop_back_to_home: "กลับสู่หน้าหลัก",
    add_prop_validation_error: "กรุณาตรวจสอบข้อมูล:",

    // Step 2
    step2_sale_rent_title: "ต้องการขายหรือปล่อยเช่า",
    step2_i_want_sell: "ฉันต้องการขาย",
    step2_i_want_rent: "ฉันต้องการปล่อยเช่า",
    step2_i_want_both: "ฉันต้องการขายและปล่อยเช่า",
    step2_property_type_title: "ประเภทอสังหาริมทรัพย์",
    step2_house_single: "บ้านเดี่ยว",
    step2_townhouse: "ทาวน์โฮม",
    step2_condo: "คอนโดมิเนียม",
    step2_land: "ที่ดิน",
    step2_commercial: "อาคารพาณิชย์",
    step2_office: "สำนักงาน",
    step2_is_project_title: "บ้านเดี่ยวของคุณอยู่บนโครงการใช่หรือไม่?",
    step2_not_project: "ไม่ใช่ (บ้านเดี่ยว/คอนโดเดี่ยว)",
    step2_is_project: "ใช่ (โครงการหลายยูนิต)",
    step2_rental_period_title: "ระยะเวลาเช่าขั้นต่ำ",
    step2_select_period: "เลือกระยะเวลา",
    step2_3_months: "3 เดือน",
    step2_6_months: "6 เดือน",
    step2_9_months: "9 เดือน",
    step2_12_months: "12 เดือน",
    step2_pin_location_title: "ปักหมุดเพื่อหาโครงการหรือที่อยู่บ้านเช่าของคุณ",

    // Step 3
    step3_project_name_title: "ชื่อโครงการ",
    step3_project_name_placeholder: "บุรีลัดดา กรุงเทพเหนือ",
    step3_address_title: "ที่อยู่",
    step3_address_from_map: "ที่อยู่จากแผนที่:",
    step3_please_select_location: "กรุณาเลือกตำแหน่งบนแผนที่ก่อน",
    step3_area_title: "พื้นที่ (ตร.ม.)",
    step3_area_placeholder: "100",
    step3_price_title: "ราคา (บาท)",
    step3_price_placeholder: "5000000",
    step3_bedrooms_title: "ห้องนอน",
    step3_bathrooms_title: "ห้องน้ำ",
    step3_parking_title: "ที่จอดรถ",
    step3_house_age_title: "อายุบ้าน (ปี)",
    step3_highlights_title: "จุดเด่นของอสังหาฯ",
    step3_near_bts: "ใกล้รถไฟฟ้า",
    step3_near_highway: "ใกล้ทางด่วน",
    step3_nice_view: "วิวสวย",
    step3_add_highlight_placeholder: "เพิ่มจุดเด่นอื่นๆ...",
    step3_add_highlight_button: "เพิ่ม",
    step3_description_title: "เกี่ยวกับอสังหาฯหรือโครงการ",
    step3_description_placeholder:
      "อธิบายรายละเอียดเกี่ยวกับอสังหาฯหรือโครงการ เช่น สภาพแวดล้อม ทำเลที่ตั้ง ความสะดวกสบาย การเดินทาง ฯลฯ",
    step3_image_upload: "รูปภาพ",
    step3_image_click_to_add: "คลิกเพื่อเพิ่มรูป (เลือกได้หลายรูป)",
    step3_image_remove: "×",

    // Step 4
    step4_review_title: "ตรวจสอบข้อมูลประกาศ",
    step4_review_desc: "กรุณาตรวจสอบข้อมูลให้ถูกต้องก่อนเผยแพร่ประกาศ",
    step4_basic_info_title: "ข้อมูลพื้นฐาน",
    step4_detail_info_title: "ข้อมูลรายละเอียด",
    step4_address_info_title: "ที่อยู่",
    step4_description_info_title: "เกี่ยวกับอสังหาฯหรือโครงการ",
    step4_images_info_title: "รูปภาพ",
    step4_sale_type_sell: "ขาย",
    step4_sale_type_rent: "เช่า",
    step4_sale_type_both: "ขายและเช่า",
    step4_is_project_yes: "ใช่ (โครงการหลายยูนิต)",
    step4_is_project_no: "ไม่ใช่ (บ้านเดี่ยว/คอนโดเดี่ยว)",
    step4_rental_3_months: "3 เดือน",
    step4_rental_6_months: "6 เดือน",
    step4_rental_9_months: "9 เดือน",
    step4_rental_12_months: "12 เดือน",
    step4_area_unit: "ตร.ม.",
    step4_price_unit: "บาท",
    step4_bedroom_studio: "สตูดิโอ",
    step4_bedroom_rooms: "ห้อง",
    step4_bathroom_rooms: "ห้อง",
    step4_parking_none: "ไม่มี",
    step4_parking_cars: "คัน",
    step4_house_age_new: "สร้างใหม่",
    step4_house_age_years: "ปี",
    step4_not_specified: "ไม่ได้ระบุ",
    step4_publish_button: "เผยแพร่ประกาศ",
    step4_saving: "กำลังบันทึก...",
    step4_sale_type_label: "ประเภทการขาย:",
    step4_property_type_label: "ประเภทอสังหา:",
    step4_is_project_label: "บ้านเดี่ยวอยู่บนโครงการ:",
    step4_rental_period_label: "ระยะเวลาเช่าขั้นต่ำ:",
    step4_project_name_label: "ชื่อโครงการ:",
    step4_area_label: "พื้นที่:",
    step4_price_label: "ราคา:",
    step4_bedrooms_label: "ห้องนอน:",
    step4_bathrooms_label: "ห้องน้ำ:",
    step4_parking_label: "ที่จอดรถ:",
    step4_house_age_label: "อายุบ้าน:",
  },
  en: {
    language_th: "ไทย",
    language_en: "EN",
    buy: "Buy",
    rent: "Rent",
    real_estate: "Real estate",
    new_real_estate: "New real estate",
    new_projects: "New projects",
    post_listing: "Post listing",
    agent: "Agent",
    profile: "Profile",
    login: "Login",
    search: "Search",
    search_placeholder: "Search project, BTS/MRT, district...",

    // Common
    back: "Back",
    back_to_home: "Back to home",
    loading: "Loading...",
    error_loading: "Error loading data",
    confirm: "Confirm",
    close: "Close",
    processing: "Processing...",

    // Featured Property
    featured_property_title:
      "New projects near BTS/MRT, convenient transportation",
    featured_property_price: "Starting from 5.2 million baht",
    featured_property_total_units: "Total project units",
    featured_property_room_size: "Room size",
    featured_property_price_per_sqm: "Price per square meter",
    featured_property_maintenance_fee: "Maintenance fee",
    featured_property_view_details: "View project details",

    // Property tags
    tag_new_project: "New project",
    tag_housing_estate: "Housing estate",
    tag_new_housing_estate: "New housing estate project",

    // Property card & detail
    property_card_area_unit: "sq.m.",
    property_card_bedrooms_label: "Bed",
    property_card_bathrooms_label: "Bath",
    property_card_parking_label: "Car",
    property_card_badge_sale_rent: "Sale/Rent",
    property_card_badge_rent: "For Rent",
    property_card_badge_sale: "For Sale",
    property_card_price_suffix: "THB",
    property_card_price_per_month_suffix: "/ month",
    property_card_view_suffix: "views",
    property_card_negotiation_name_label: "Name:",
    property_card_negotiation_price_label: "Offered price:",
    property_card_negotiation_reason_label: "Reason:",
    property_card_negotiation_phone_label: "Phone:",
    property_card_negotiation_email_label: "Email:",
    property_card_appointment_name_label: "Name:",
    property_card_appointment_phone_label: "Phone:",
    property_card_appointment_email_label: "Email:",
    property_card_appointment_date_label: "Appointment date:",
    property_card_appointment_note_label: "Notes:",
    property_card_download_document: "Download document",
    property_card_create_contract: "Create contract",
    property_card_confirm_button: "Confirm",
    property_card_reject_button: "Reject",
    property_card_status_sold: "Sold",
    property_card_status_rented: "Rented",
    property_card_view_on_map: "View on map",
    property_card_update_button: "Update",
    property_card_contract_heading: "Purchase Agreement",
    property_card_contract_buyer_label: "Buyer:",
    property_card_contract_seller_label: "Seller:",
    property_card_contract_property_label: "Property:",
    property_card_contract_price_label: "Price:",
    property_card_contract_date_label: "Date:",
    property_card_confirmation_title: "Confirm appointment",
    property_card_confirmation_message:
      "Do you want to confirm this appointment?",
    property_card_confirm_success_title: "Confirmation successful",
    property_card_confirm_success_message: "The appointment has been confirmed",
    property_card_cancel_title: "Cancel appointment",
    property_card_cancel_message: "Do you want to cancel this appointment?",
    property_card_cancel_success_title: "Cancellation successful",
    property_card_cancel_success_message: "The appointment has been cancelled",
    property_card_price_label: "Price",
    property_card_share_failure: "Unable to share",
    property_card_clipboard_success: "Link copied",
    property_card_share_prefix: "Price",

    property_detail_loading_description:
      "Please wait while we load property data",
    property_detail_error_title: "Error",
    property_detail_error_description: "Unable to load property information",
    property_detail_not_found_title: "Property not found",
    property_detail_not_found_description:
      "The property you are looking for does not exist",
    property_detail_reset_gallery_tooltip: "Click to return to the first image",
    property_detail_price_label: "Price:",
    property_detail_area_title: "Area",
    property_detail_features_area: "Area",
    property_detail_features_bedrooms: "Bed",
    property_detail_features_bathrooms: "Bath",
    property_detail_features_parking: "Car",
    property_detail_features_condition: "Condition",
    property_detail_features_type: "Type",
    property_detail_highlight_title: "Highlights",
    property_detail_highlight_empty: "No highlights provided",
    property_detail_read_more: "See all",
    property_detail_read_less: "See less",
    property_detail_description_title: "About this property",
    property_detail_description_empty: "No description provided",
    property_detail_location_title: "Location",
    property_detail_similar_title: "Similar properties",
    property_detail_scroll_left: "Scroll left",
    property_detail_scroll_right: "Scroll right",
    property_detail_no_similar: "No similar properties found",
    property_detail_contact_title: "Contact about this property",
    property_detail_agent_label: "Listing agent",
    property_detail_view_phone: "View phone number",
    property_detail_toast_success_added: "Added to favorites",
    property_detail_toast_success_removed: "Removed from favorites",
    property_detail_toast_error: "An error occurred. Please try again",
    property_detail_share_not_supported:
      "Your browser does not support sharing",
    property_detail_login_message: "Please sign in",
    property_detail_payment_required: "Please upgrade to contact the seller",
    property_detail_modal_close: "Close",
    property_detail_modal_message_login: "Please sign in",
    property_detail_modal_message_payment:
      "Please upgrade to contact the seller",
    property_detail_toast_clipboard_success: "Link copied",
    property_detail_load_more_icon: "See more",
    property_detail_agent_role: "Listing agent",
    property_detail_price_not_available: "Price not specified",
    property_detail_area_unit: "sq.m.",
    property_detail_feature_unit: "sq.m.",
    property_detail_feature_type_sale_rent: "Sale/Rent",
    property_detail_back_button: "Back",
    property_detail_notify_phone_success: "Notification sent",
    property_detail_notify_phone_error: "Unable to send notification",
    property_detail_loading_title: "Loading property...",
    property_detail_error_back_home: "Back to home",
    property_detail_contact_button_label: "View phone number",
    property_detail_mobile_contact_title: "Contact about this property",
    property_detail_unavailable: "N/A",
    property_detail_address_unavailable: "Address not specified",
    property_detail_default_share_title: "Property",
    property_detail_project_name_unavailable: "Unnamed project",
    property_detail_default_property_title: "Property",

    // Dashboard root
    dashboard_title: "Dashboard",
    please_login: "Please sign in",

    // Sidebar menu items
    sidebar_dashboard: "Dashboard",
    sidebar_my_account: "My Account",
    sidebar_my_listings: "My Listings",
    sidebar_favorites: "Favorites",
    sidebar_packages: "Packages",
    sidebar_notifications: "Notifications",
    sidebar_logout: "Logout",

    // Header navigation menu
    header_buy: "Buy",
    header_sell: "Sell",
    header_rent: "Rent",
    header_real_estate: "Real Estate",
    header_new_real_estate: "New Real Estate",
    header_new_projects: "New Projects",
    header_post_listing: "Post Listing",
    header_profile: "Profile",
    header_language_thai: "ภาษาไทย",
    header_language_english: "English",
    you_are_not_logged_in_description:
      "You are not signed in. Please sign in to use the dashboard.",
    admin_dashboard: "Admin dashboard",
    welcome_admin: "Welcome, admin",
    manage_my_account: "Manage my account",
    open_super_admin_login_new_window: "Open Super Admin (new window)",
    note_super_admin:
      "Note: Super Admin is separate from the main site. Please use the link above to sign in.",
    checking_user_info: "Checking user information...",
    please_wait_redirect:
      "Please wait while we redirect you to the appropriate dashboard.",
    welcome: "Welcome",
    redirecting: "Redirecting to the appropriate page...",
    logout: "Log out",
    switch_to_customer: "Switch to Customer",
    switch_to_agent: "Switch to Agent",

    // Favorites
    favorites_title: "Favorites",
    search_placeholder_favorites: "Search project, price",
    compare_price: "Compare",
    all_properties: "All",
    sale: "Sale",
    no_favorites_title: "No favorites yet",
    no_favorites_desc:
      "Start adding properties you like to your favorites list.",
    start_search: "Start searching",

    // Favorites page specific
    favorites_page_title: "Favorites",
    favorites_compare_selected: "Compare Selected Items",
    favorites_items_count: "items",
    favorites_table_close: "Close table",
    favorites_table_minimize: "Click to expand table",
    favorites_compare_alert: "Please select at least 2 items to compare",
    favorites_remove_success: "Removed from favorites",
    favorites_add_success: "Added to favorites",
    favorites_remove_error: "An error occurred. Please try again",
    favorites_share_success: "Shared successfully!",
    favorites_copy_success: "Link copied successfully!",
    favorites_share_error: "Unable to share. Please try again",
    favorites_login_required: "Please login to use this feature",
    favorites_rent: "For Rent",
    favorites_sale: "For Sale",
    favorites_popular: "Popular",
    favorites_featured: "Featured",
    favorites_views: "Views",
    favorites_times: "times",
    favorites_remove_from_favorites: "Remove from favorites",
    favorites_add_to_favorites: "Add to favorites",
    favorites_share_property: "Share this property",
    favorites_select_for_compare: "Select for comparison",
    favorites_deselect: "Deselect",
    favorites_rooms: "rooms",
    favorites_cars: "cars",
    favorites_others: "others",
    favorites_no_data: "No data",
    favorites_project_facilities: "Project Facilities",
    favorites_area_size_label: "Area size",
    favorites_usable_area_label: "Usable area",
    favorites_comparison_list_label: "Item",
    favorites_property_facilities_label: "Facilities",
    list: "Item",
    price: "Price",
    bedrooms: "Bedrooms",
    bathrooms: "Bathrooms",
    area_sqm: "Area (sqm)",
    parking_spaces: "Parking spaces",
    house_condition: "Condition",
    highlight: "Highlight",
    nearby_places: "Nearby",
    description: "Description",
    project_facilities: "Project facilities",
    created_date: "Created date",
    unspecified: "Unspecified",
    no_data: "No data",

    // Notifications
    notifications: "Notifications",
    all: "All",
    unread: "Unread",
    no_notifications: "No notifications",
    previous_notifications: "View previous notifications",
    show_all_notifications: "Show all notifications",
    collapse_notifications: "Collapse notifications",
    from: "From:",
    system: "System",
    read_label: "read",
    property_not_found: "Property not found",
    customer_already_exists: "This customer already has this property",
    duplicate_customer_title: "Warning",
    duplicate_customer_message: "This customer already has this property",
    update_failed: "Failed to update data",
    customer_added_success: "Customer added successfully",
    customer_notification_title: "Rental Successful",
    customer_notification_message:
      "You have been added as the owner of this property",

    // Listings
    my_listings: "My listings",
    search_placeholder_listings: "Search project, price",
    add_listing: "Add listing",
    filters: "Filters",
    negotiating: "Negotiating",
    scheduling: "Scheduling",
    contracted: "Contracted",
    update_every_3_months: "Update every 3 months",
    checking_user_status: "Checking user status...",
    loading_listings: "Loading listings...",
    not_logged_in_view_my_listings: "Please sign in to view your listings",
    search_no_results: "No listings match your search",
    empty_all: "No listings yet",
    empty_negotiating: "No listings under negotiation",
    empty_scheduling: "No scheduled listings",
    empty_contracted: "No contracted listings",
    empty_update_reminder: "No listings to update",
    show_filters: "Show filters",
    loading_negotiations: "Loading negotiation requests...",
    loading_appointments: "Loading appointments...",
    no_negotiations_message: "No negotiation requests yet",
    no_appointments_message: "No appointments yet",
    no_contracts_detail: "Found {count} appointments but no contract data",
    listings_filtered_out_detail:
      "Found {count} listings but all were filtered out",
    listing_hidden_due_status:
      "This listing is hidden because it has been sold/rented for 3 days",
    status_sold_label: "already sold",
    status_rented_label: "already rented",
    listing_expiry_warning:
      "This listing will be removed in {days} days because it is {status}",
    listing_no_description: "No description provided",
    listing_no_highlight: "No highlight information",
    listing_no_nearby_info: "No nearby information",
    action_edit: "Edit",
    action_delete: "Delete",
    action_mark_as_sold: "Mark as sold",
    action_mark_as_rented: "Mark as rented",
    delete_confirmation_title: "Delete listing",
    delete_confirmation_body:
      "Are you sure you want to delete this listing? This action cannot be undone.",
    edit_listing_modal_title: "Edit listing",
    edit_listing_modal_body: "Do you want to edit this listing?",
    update_form_property_not_found: "Listing to update not found",
    error_delete_listing: "An error occurred while deleting the listing",
    error_update_status: "An error occurred while updating the status",
    notification_expiring_listing: "Listing expiring soon",
    no_update_cards_customer: "No cards associated with you",
    no_update_cards_rented: 'No cards with status "rented"',
    account_title: "Account information",
    account_profile_tab: "Profile details",
    account_security_tab: "Security",
    account_notifications_tab: "Notifications",
    account_manage_profile: "Manage your personal information",
    account_manage_role_info: "Additional info based on your role",
    account_loading: "Loading...",
    account_loading_agent: "Loading agent information...",
    account_loading_customer: "Loading customer information...",
    account_agent_not_found: "No agent information found",
    account_customer_not_found: "No customer information found",
    account_no_profile_role: "No profile data for this role",
    account_security_title: "Security",
    account_security_desc: "Change passwords and manage account security",
    account_password_label: "Password",
    account_password_hint: "Click the button below to change your password",
    account_change_password: "Change password",
    account_notifications_title: "Notifications",
    account_notifications_desc: "Manage how you receive updates from us",
    account_notifications_email: "Email notifications",
    account_notifications_email_desc: "Receive news and updates via email",
    account_notifications_sms: "SMS notifications",
    account_notifications_sms_desc: "Receive important alerts via SMS",
    account_profile_info: "Profile information",
    account_edit_first_name: "Edit first name",
    account_edit_last_name: "Edit last name",
    account_edit_phone: "Edit phone",
    account_role_label: "Role",
    account_agent_company_name: "Company name",
    account_agent_license: "License number",
    account_agent_address: "Address",
    account_agent_property_types: "Property types",
    account_agent_service_areas: "Service areas",
    account_agent_status: "Status",
    account_customer_address: "Address",
    account_customer_preferred_location: "Preferred locations",
    account_customer_budget_range: "Budget range",
    account_customer_interested_types: "Interested property types",
    agent_dashboard_title: "Agent Dashboard",
    agent_dashboard_loading: "Loading dashboard...",
    agent_dashboard_missing_id: "Please provide an agent ID",
    agent_dashboard_properties_status: "Properties by status",
    agent_dashboard_properties_posted: "Properties posted (last 12 months)",
    agent_dashboard_properties_dataset: "Properties",
    agent_dashboard_top_categories: "Top property categories",
    agent_dashboard_appointments_status: "Appointments by status",
    agent_dashboard_negotiations_status: "Negotiations by status",
    agent_dashboard_appointments_last_12m: "Appointments (last 12 months)",
    agent_dashboard_appointments_dataset: "Appointments",
    agent_dashboard_notifications_last_30d: "Notifications (last 30 days)",
    agent_dashboard_notifications_dataset: "Notifications",

    // Modals
    accept_offer_question: "Accept this offer?",
    accept_offer_note:
      "Once confirmed, a notification will be sent to the bidder.",
    accept_offer_success: "Offer accepted!",
    accept_offer_success_note:
      "A notification will be sent to the bidder and this card will be removed.",
    reject_offer_question: "Reject this offer?",
    please_specify_reason: "Please specify a reason",
    other_reason: "Other (please specify)",
    enter_other_reason: "Enter other reason",
    reject_confirm: "Confirm rejection",
    reject_success: "Offer rejected successfully!",

    // Home page
    loading_properties: "Loading properties...",
    home_new_properties_title:
      "New properties! Ready to move/invest, great price, prime locations",
    home_rental_properties_title:
      "Rental listings: house/condo/land, ready to move in, great price, great locations!",
    home_sale_properties_title:
      "Sale listings: house/condo/land in prime locations, great for living or investing",
    home_sale_rent_properties_title:
      "Sale/Rent listings: houses/condos in prime lifestyle areas near malls and dining",
    popular_locations: "Popular locations",
    view_all: "View all",
    // Location names
    location_sukhumvit: "Sukhumvit",
    location_rama9: "Rama 9",
    location_ladprao: "Lat Phrao Intersection",
    location_sathorn: "Sathorn",

    // All properties page
    all_props_search_placeholder: "Search location, project or keyword",
    filter_type_label: "Type",
    filter_rental_label: "Rent/Sale",
    filter_rooms_label: "Bedrooms",
    filter_price_label: "Price",
    show_map: "Show map",
    clear_filters: "Clear filters",
    results_title: "Property search results",
    results_showing: "Showing",
    results_of: "of",
    prev: "Previous",
    next: "Next",
    no_properties_title: "No properties found",
    no_properties_from_db_title: "No listings available",
    no_properties_from_db_desc:
      "There are currently no listings from the database",
    try_adjust_filters: "Try adjusting filters or search term",

    // Map page
    back_label: "Back",
    map_search_placeholder: "Search area, project or keyword",
    property_type_all: "All property types",
    property_type_condo: "Condo",
    property_type_house: "House",
    property_type_townhouse: "Townhouse",
    property_type_land: "Land",
    property_type_commercial: "Commercial",
    listing_type_all: "All listings",
    listing_type_rent: "Rent",
    listing_type_sale: "Sale",
    price_label: "Price",
    sort_new_old: "Projects (newest first)",
    sort_price_asc: "Price (low to high)",
    sort_price_desc: "Price (high to low)",
    loading_map: "Loading map...",
    not_found_list: "No results found",

    // Add-property progress
    progress_step1_intro: "Posting introduction",
    progress_step2_basic: "Fill basic details",
    progress_step3_property: "Fill property details",
    progress_step4_review: "Review information",

    // Project titles and descriptions
    project_grand_title: "THE GRAND RESIDENCE",
    project_grand_location: "Sukhumvit - Bangkok",
    project_grand_description:
      "Modern luxury condominium project near BTS, prime location, near shopping malls and complete facilities",
    project_grand_total_units: "406 units",
    project_grand_room_size: "27-32.7 sq.m.",
    project_grand_price_per_sqm: "(57,098 baht/sq.m.)",
    project_grand_maintenance_fee: "18 baht",
    project_grand_price: "Starting from 5.5 million baht",
    project_luxe_title: "THE LUXE CONDOMINIUM",
    project_luxe_location: "Rama 9 - Bangkok",
    project_luxe_description:
      "Luxury condominium in the city center with premium design, high-quality materials, complete common facilities, near MRT and expressway",
    project_luxe_total_units: "325 units",
    project_luxe_room_size: "35-65 sq.m.",
    project_luxe_price_per_sqm: "(85,000 baht/sq.m.)",
    project_luxe_maintenance_fee: "22 baht",
    project_luxe_price: "Starting from 6.8 million baht",
    project_riverside_title: "RIVERSIDE VILLA",
    project_riverside_location: "Charoen Nakhon - Bangkok",
    project_riverside_description:
      "Detached house by the Chao Phraya River with peaceful atmosphere, beautiful view, spacious living area, convenient transportation both by water and land",
    project_riverside_total_units: "150 units",
    project_riverside_room_size: "250-350 sq.m.",
    project_riverside_price_per_sqm: "(120,000 baht/sq.m.)",
    project_riverside_maintenance_fee: "35 baht",
    project_riverside_price: "Starting from 15.5 million baht",

    // Footer
    footer_company_name: "Teedin",
    footer_company_description:
      "Real estate platform that helps you easily find houses, condos, and land",
    footer_about_us: "About us",
    footer_about_teedin: "About Teedin",
    footer_contact_us: "Contact us",
    footer_join_us: "Join us",
    footer_our_services: "Our services",
    footer_buy_house: "Buy house",
    footer_rent_house: "Rent house",
    footer_sell_house: "Sell house",
    footer_appraise_price: "Appraise price",
    footer_follow_us: "Follow us",
    footer_social_facebook: "Facebook",
    footer_social_instagram: "Instagram",
    footer_social_twitter: "Twitter",
    footer_copyright: "© 2025 Teedin. All rights reserved.",
    footer_privacy_policy: "Privacy Policy",
    // Rental types
    rental_type_rent: "Rent",
    rental_type_sale: "Sale",

    // Price filter
    price_range_label: "Price Range (Baht)",
    min_price_label: "Min Price",
    max_price_label: "Max Price",
    reset_button: "Reset",
    apply_button: "Apply",

    // Refresh button
    refresh_data: "Refresh Data",

    // Pagination
    previous_page: "← Previous",
    next_page: "Next →",
    page_label: "Page",
    of_label: "of",

    // MapPicker component
    map_pick_open_edit: "Click to edit location",
    map_pick_open_select: "Click to pick a location on the map",
    map_pick_not_selected: "No location selected",
    map_pick_title: "Pick a location on the map",
    map_pick_search_placeholder: "Search address e.g. Sukhumvit, Bangkok",
    map_pick_search_button: "Search",
    map_pick_loading: "Loading map...",
    map_pick_instructions:
      "Click the map to choose a location, or search above",
    map_pick_selected_address_label: "Selected address:",
    map_pick_coordinates_label: "Coordinates:",
    map_pick_select_prompt: "Please choose a location on the map",
    cancel: "Cancel",
    confirm_select_location: "Confirm location",
    map_pick_search_not_found: "Address not found. Please try again.",
    address_not_found: "Address not found",

    // Add-property Step1 Introduction
    step1_heading: "🌟 List your property easily in just a few steps! 🌟",
    step1_intro_line1_prefix:
      "Teedin Easy helps you post quickly and conveniently using",
    step1_intro_maps: " Maps ",
    step1_intro_line1_suffix: "to locate your property. Just",
    step1_intro_pin: " pin ",
    step1_intro_line2:
      "and the system will auto-fetch the address and project details, reducing manual input so you can sell or rent faster!",
    step1_how_title: "✅ How to post",
    step1_step1: "1. Choose Sell, Rent, or both",
    step1_step2: "2. Select property type – House, Condo, Land, or others",
    step1_step3: "3. Pin on the map – set your property's location",
    step1_step4: "4. Review details – auto-fetched project info (editable)",
    step1_step5: "5. Upload photos – make your listing attractive",
    step1_step6: "6. Publish – your listing becomes visible immediately!",
    step1_why_title: "🔍 Why Teedin Easy?",
    step1_why_1: "✅ Easy pinning – no manual address input",
    step1_why_2: "✅ Save time – minimal edits with prefilled project info",
    step1_why_3: "✅ Reach buyers faster – show listings to active seekers",
    step1_start_button: "Start",
    step1_alert_title: "Register as Agent to start posting",
    step1_alert_desc: "Please register as an Agent before posting",
    step1_register_agent: "Register Agent",
    step1_switch_role_title: "Switch to Agent to post listing",
    step1_switch_role_desc:
      "You are currently using as a customer. Please switch to agent account to post a listing.",
    step1_switch_to_agent: "Switch to Agent",

    // AgentRegisterModal
    agent_modal_title: "Register as Agent",
    agent_modal_description_line1:
      "Please contact our staff to register as an Agent",
    agent_modal_description_line2: "or register online",
    agent_modal_register_online: "Register online",
    agent_modal_register_loading: "Registering...",
    agent_modal_contact_staff: "Contact staff",
    agent_modal_close: "Close",
    agent_modal_redirecting: "Redirecting you to Agent registration...",
    agent_modal_contacting: "Contacting staff...",

    // Add-property page
    add_prop_loading: "Loading...",
    add_prop_data_restored: "Form data restored",
    add_prop_success_title: "Listing published successfully!",
    add_prop_success_desc_line1: "Please wait for listing review",
    add_prop_success_desc_line2:
      "Your listing will be published after approval",
    add_prop_view_my_listings: "View my listings",
    add_prop_back_to_home: "Back to home",
    add_prop_validation_error: "Please check the data:",

    // Step 2
    step2_sale_rent_title: "Want to sell or rent",
    step2_i_want_sell: "I want to sell",
    step2_i_want_rent: "I want to rent",
    step2_i_want_both: "I want to sell and rent",
    step2_property_type_title: "Property type",
    step2_house_single: "Single house",
    step2_townhouse: "Townhouse",
    step2_condo: "Condominium",
    step2_land: "Land",
    step2_commercial: "Commercial building",
    step2_office: "Office",
    step2_is_project_title: "Is your house part of a project?",
    step2_not_project: "No (single house/condo)",
    step2_is_project: "Yes (multi-unit project)",
    step2_rental_period_title: "Minimum rental period",
    step2_select_period: "Select period",
    step2_3_months: "3 months",
    step2_6_months: "6 months",
    step2_9_months: "9 months",
    step2_12_months: "12 months",
    step2_pin_location_title:
      "Pin to find your project or rental house location",

    // Step 3
    step3_project_name_title: "Project name",
    step3_project_name_placeholder: "Buri Lad Bangkok North",
    step3_address_title: "Address",
    step3_address_from_map: "Address from map:",
    step3_please_select_location: "Please select location on map first",
    step3_area_title: "Area (sqm)",
    step3_area_placeholder: "100",
    step3_price_title: "Price (Baht)",
    step3_price_placeholder: "5000000",
    step3_bedrooms_title: "Bedrooms",
    step3_bathrooms_title: "Bathrooms",
    step3_parking_title: "Parking",
    step3_house_age_title: "House age (years)",
    step3_highlights_title: "Property highlights",
    step3_near_bts: "Near BTS/MRT",
    step3_near_highway: "Near highway",
    step3_nice_view: "Nice view",
    step3_add_highlight_placeholder: "Add other highlights...",
    step3_add_highlight_button: "Add",
    step3_description_title: "About property or project",
    step3_description_placeholder:
      "Describe details about the property or project such as environment, location, convenience, transportation, etc.",
    step3_image_upload: "Images",
    step3_image_click_to_add:
      "Click to add images (multiple selection allowed)",
    step3_image_remove: "×",

    // Step 4
    step4_review_title: "Review listing information",
    step4_review_desc: "Please verify the information before publishing",
    step4_basic_info_title: "Basic information",
    step4_detail_info_title: "Detail information",
    step4_address_info_title: "Address",
    step4_description_info_title: "About property or project",
    step4_images_info_title: "Images",
    step4_sale_type_sell: "Sale",
    step4_sale_type_rent: "Rent",
    step4_sale_type_both: "Sale and rent",
    step4_is_project_yes: "Yes (multi-unit project)",
    step4_is_project_no: "No (single house/condo)",
    step4_rental_3_months: "3 months",
    step4_rental_6_months: "6 months",
    step4_rental_9_months: "9 months",
    step4_rental_12_months: "12 months",
    step4_area_unit: "sqm",
    step4_price_unit: "baht",
    step4_bedroom_studio: "Studio",
    step4_bedroom_rooms: "rooms",
    step4_bathroom_rooms: "rooms",
    step4_parking_none: "None",
    step4_parking_cars: "cars",
    step4_house_age_new: "New build",
    step4_house_age_years: "years",
    step4_not_specified: "Not specified",
    step4_publish_button: "Publish listing",
    step4_saving: "Saving...",
    step4_sale_type_label: "Sale type:",
    step4_property_type_label: "Property type:",
    step4_is_project_label: "House in project:",
    step4_rental_period_label: "Minimum rental period:",
    step4_project_name_label: "Project name:",
    step4_area_label: "Area:",
    step4_price_label: "Price:",
    step4_bedrooms_label: "Bedrooms:",
    step4_bathrooms_label: "Bathrooms:",
    step4_parking_label: "Parking:",
    step4_house_age_label: "House age:",
  },
};

function writeLangCookie(language: Language) {
  try {
    const oneYearSeconds = 60 * 60 * 24 * 365;
    document.cookie = `lang=${language}; path=/; max-age=${oneYearSeconds}`;
  } catch {
    // ignore
  }
}

export function LanguageProvider({
  initialLanguage = "th",
  children,
}: {
  initialLanguage?: Language;
  children: React.ReactNode;
}) {
  const [language, setLanguageState] = useState<Language>(initialLanguage);

  // Keep <html lang> in sync for immediate effect on CSR
  useEffect(() => {
    if (typeof document !== "undefined") {
      document.documentElement.lang = language;
    }
  }, [language]);

  const setLanguage = useCallback((newLanguage: Language) => {
    setLanguageState(newLanguage);
    try {
      localStorage.setItem("lang", newLanguage);
    } catch {
      // ignore
    }
    writeLangCookie(newLanguage);
  }, []);

  // Initialize from localStorage if available to persist across reloads
  useEffect(() => {
    try {
      const saved = localStorage.getItem("lang");
      if (saved === "th" || saved === "en") {
        setLanguageState(saved);
      }
    } catch {
      // ignore
    }
  }, []);

  const t = useCallback(
    (key: string) => {
      const langTable = TRANSLATIONS[language] ?? TRANSLATIONS.th;
      return langTable[key] ?? key;
    },
    [language]
  );

  const value = useMemo<LanguageContextValue>(
    () => ({ language, setLanguage, t }),
    [language, setLanguage, t]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage(): LanguageContextValue {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return ctx;
}
